#!/bin/sh
cd "$(dirname "$0")"
if ! test -d ./frontend -a -d ./backend
then
	echo >&2 "script needs to exist in the 'py.projects.pg.org' project directory"
	exit 1
fi

mkdir -p ./root/backend || exit

# frontend
cp -r ./frontend/static/* root/ || exit

xsltproc frontend/src/index.xsl frontend/src/index.xml >root/index.html || exit
cp -r frontend/src/lib root/ || exit
cp frontend/src/ticker.xsl root/ || exit
cp frontend/src/*.css root/ || exit
cp frontend/src/*.png root/ || exit
cp frontend/src/license.txt root/ || exit

rm root/sphinx-doc-icon.png || exit
cp root/py.png root/favicon.ico || exit

python3 ./frontend/copy_documentation.py || exit
# 0.9's documentation exists in static/docs.
mv frontend/docs/* root/docs/ || exit
rmdir frontend/docs


# backend
cp -r backend/static/* root/backend || exit

xsltproc backend/src/index.xsl backend/src/index.xml >root/backend/index.html || exit
cp -r backend/src/lib root/backend/ || exit
cp backend/src/*.css root/backend/ || exit
cp backend/src/*.png root/backend/ || exit
cp backend/src/license.txt root/backend/ || exit

rm root/backend/sphinx-doc-icon.png || exit
cp root/backend/py.png root/backend/favicon.ico || exit

python3 ./backend/copy_documentation.py || exit
mv backend/docs/* root/backend/docs/ || exit
rmdir backend/docs
