#!/bin/sh
SRC=root/
DST=pgfoundry.org:/home/pgfoundry.org/groups/python/htdocs
rsync --delete-after --exclude=ticker.html --exclude=backend_commitlog.atom --exclude=commitlog.atom --exclude=mail.xml -vzr "$SRC" "$DST"
